### ISSUE TITLE
Currently CI fails on v1.5 and v1.6

### ISSUE THREAD

**Issue by hkdnet** [treasure-data/td-client-go#27]
`td-client-go` depends on `github.com/ugorji/go/codec`.
Currently (2019-06-14), `github.com/ugorji/go/codec` cannot be built by Go 1.5 and 1.6 because of the missing of the definition of `func mapRange`.

```
$ go get github.com/ugorji/go/codec
# github.com/ugorji/go/codec
../../ugorji/go/codec/encode.go:587: undefined: mapRange
```
https://travis-ci.org/treasure-data/td-client-go/jobs/545596286

This has been caused since https://github.com/ugorji/go/commit/31b118dd0628c36594c1707e7dcbbd411c705c88.
I don't know whether it is intentional or not.

**Comment by nurse** [comment]
I think we can drop Go 1.5 and 1.6.
For example they don't support recent macOS:
"Binaries built with versions of Go before 1.7 will not work correctly on Sierra."
(Sierra was new OS at that time)
https://golang.org/doc/go1.7#ports

**Comment by hkdnet** [comment]
Oh, I didn't know that. It seems reasonable to drop them.
I'll remove 1.5 and 1.6 and add 1.12 to test targets later.

**Comment by hkdnet** [comment]
Fixed by #28
